In [6]:
#import the required packages for linear and polynomial regression
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
import glob

%matplotlib inline
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix


from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

In [7]:
#lm=LinearRegression()
regr = linear_model.LinearRegression()

In [8]:
#Getting the data from the csv files 

path = r'./csse_covid_19_data/csse_covid_19_daily_reports_us/may'
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

df = pd.concat(li, axis=0, ignore_index=True)

In [9]:
#train the data
#ds = pd.read_csv('./csse_covid_19_data/csse_covid_19_daily_reports_us/may/05-05-2020.csv')

df = df.dropna()

train_x = np.asanyarray(df[[
       'Recovered', 'Active',
       'Incident_Rate', 'People_Tested', 'People_Hospitalized',
       'Mortality_Rate', 'Testing_Rate',
       'Hospitalization_Rate']])
train_y = np.asanyarray(df['Confirmed'])
#dfObj.columns.values

In [10]:
#ask = np.all(np.isnan(train_x) | np.equal(train_x, 0), axis=1)
#rain_x = train_x[~mask]
#rint (train_x)

regr.fit (train_x, train_y)

LinearRegression()

In [24]:
#Make test cases
ds = pd.read_csv('./csse_covid_19_data/csse_covid_19_daily_reports_us/04-12-2020.csv')
ds = ds.dropna()

test_x = np.asanyarray(ds[[
       'Recovered', 'Active',
       'Incident_Rate', 'People_Tested', 'People_Hospitalized',
       'Mortality_Rate', 'Testing_Rate',
       'Hospitalization_Rate']])
test_y = np.asanyarray(ds['Confirmed'])

In [12]:
y_prediction = regr.predict(test_x)

In [13]:
y_prediction

array([ 1.19422999e+02,  1.35483810e+03,  1.46326128e+03,  3.87647819e+01,
        5.07768038e+02,  2.10397489e+03,  2.16914914e+03,  4.65778146e+02,
        8.50300205e+03,  2.49030036e+04,  2.16519778e+03,  1.25221844e+02,
        7.60729846e+02,  1.30563648e+03,  2.20790335e+05,  1.16822808e+02,
        2.61812591e+03,  2.49001674e+03,  5.58003195e+02,  6.91122149e+03,
        1.59559995e+04,  7.71505336e+02,  1.43575516e+02, -2.98539196e+02])

In [14]:
test_y

array([   272,   1280,   1625,    133,    499,   1587,   1963,    633,
         8225,  24244,   1621,    387,    929,   1245, 189033,    308,
         1970,   2665,    730,   5508,  13677,    727,    593,    270],
      dtype=int64)

In [15]:
poly = PolynomialFeatures(degree=3)
train_x_poly = poly.fit_transform(train_x)

In [16]:
regr.fit (train_x_poly , train_y)

LinearRegression()

In [17]:
test_x_poly = poly.fit_transform(test_x)

In [18]:
y_prediction = regr.predict(test_x_poly )

In [19]:
y_prediction

array([4.78049760e+02, 2.02601116e+03, 2.01749349e+03, 2.98462988e+02,
       1.30630513e+03, 2.61519149e+03, 3.36741109e+03, 1.25508062e+03,
       9.39965455e+03, 2.47342183e+04, 4.31536432e+03, 7.32651451e+02,
       1.50276680e+03, 2.05021615e+03, 4.53157173e+05, 6.46117624e+02,
       4.48022079e+03, 2.66579999e+03, 1.01295780e+03, 8.58337191e+03,
       1.51736169e+04, 7.91557914e+02, 8.09945808e+02, 3.20099405e+02])

In [20]:
test_y

array([   272,   1280,   1625,    133,    499,   1587,   1963,    633,
         8225,  24244,   1621,    387,    929,   1245, 189033,    308,
         1970,   2665,    730,   5508,  13677,    727,    593,    270],
      dtype=int64)

In [21]:
from sklearn.metrics import mean_squared_error
#print (mean_squared_error(test_y, y_prediction))
print (y_prediction - test_y)

[2.06049760e+02 7.46011160e+02 3.92493490e+02 1.65462988e+02
 8.07305132e+02 1.02819149e+03 1.40441109e+03 6.22080624e+02
 1.17465455e+03 4.90218285e+02 2.69436432e+03 3.45651451e+02
 5.73766801e+02 8.05216150e+02 2.64124173e+05 3.38117624e+02
 2.51022079e+03 7.99992079e-01 2.82957805e+02 3.07537191e+03
 1.49661689e+03 6.45579139e+01 2.16945808e+02 5.00994052e+01]


In [22]:
from sklearn.metrics import mean_absolute_error
print (mean_absolute_error(test_y, y_prediction))

11817.322420808392


In [25]:
X = df[[
       'Recovered', 'Active',
       'Incident_Rate', 'People_Tested', 'People_Hospitalized',
       'Mortality_Rate', 'Testing_Rate',
       'Hospitalization_Rate']].values
y = df['Confirmed'].values

In [26]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)

In [32]:
from sklearn import svm
clf = svm.SVC(kernel='poly')
clf.fit(X_train, y_train)

SVC(kernel='poly')

In [33]:
Predicion = clf.predict(X_test)

In [34]:
from sklearn.metrics import f1_score
f1_score(y_test, Predicion, average='weighted')

7.142857142857143e-05

In [35]:
Predicion

array([   479,    479,    479,    479,    479,    479,    479, 351371,
          479,    479,    479,    479,    479,    479,    479,    479,
          479,    479,    479,    479,    479,    479,    479,    479,
          479,    479,    479,    479,  18412,    479,    479,    479,
          479,    479, 316415,    479,    479,    479,    479,    479,
          479,    479,    479,    479,    479,    479,    479,    479,
          479,    479,    479,    479,    479,    479,    479,  18412,
          479,    479,    479,    479,  18412,    479,    479,    479,
          479,    479,    479,    479,    479,    479, 369660,    479,
          479, 363836,    479,    479,    479,  18412,    479,    479,
          479,    479,    479,    479,    479,    479,    479,    479,
        18412,    479,    479,    479,    479,    479,    479,    479,
          479,    479,    479,    479,    479,    479,    479,    479,
          479,    479,    479, 321192,    479, 155764,    479, 362764,
      

In [36]:
y_test

array([  4131,   6625,   9056,  14985,  15668,   6251,  45495, 352845,
         7851,   8686,   3556,    579,  17832,   2229,   7444,   4243,
        28665,  25462,   4563,    838,  20257,  15229,   3437,   1761,
        43531,  14969,  37968,   2061,  19785,   6440,  13260,  34061,
         3663,  10960, 318953,   2635,  32984,   4085,   4086,   8901,
         5503,   1603,  34574,   2106,   5680,    649,  16635,    850,
         9933,   5069,   8909,  20257,   7441,  42323,  10096,  16960,
         7705,    596,  14819,   2127,  17359,  28163,  12917,   3864,
        15348,   3927,   5364,    485,   6418,   5938, 368284,   8640,
          638, 364965,  34333,  41559,  13458,  41401,    635,  19375,
         3801,   8426,    458,   5595,  10801,  12795,   4490,  14065,
        68087,   9533,  42201,  11394,    479,   2481,   2109,  11799,
         5130,   6418,   9707,   9090,   7792,  41762,   8566,    468,
        10526,  23196,  16530, 323978,   1123, 156628,  24552, 361515,
      

In [37]:
X_train

array([[1.75200000e+03, 2.87900000e+03, 1.42523171e+02, ...,
        5.08300881e+00, 1.68401687e+03, 2.89198606e+01],
       [7.72800000e+03, 5.20400000e+03, 2.30367575e+02, ...,
        3.58607321e+00, 2.88046202e+03, 1.61112354e+01],
       [5.97580000e+04, 2.55652000e+05, 1.76343550e+03, ...,
        8.05740254e+00, 6.67619157e+03, 2.16973570e+01],
       ...,
       [6.07960000e+04, 2.59387000e+05, 1.79006815e+03, ...,
        8.05468768e+00, 7.08722172e+03, 2.15841738e+01],
       [6.65000000e+02, 9.17000000e+03, 9.63316565e+02, ...,
        3.62567369e+00, 7.49253559e+03, 1.10044096e+01],
       [1.83000000e+03, 8.17000000e+02, 3.62553201e+02, ...,
        7.87106447e-01, 2.54290032e+03, 7.90854573e+00]])

In [38]:
y_train

array([  4879,  13413, 343051,   2351,   6943,    493,   7130,  24256,
        44424,   9652,  20111,   5245,   2588,   2178,   1226,   6853,
         2595,  35903,   6625,    643,   2260,  36986,   2520,    653,
       330407,   5398,   2631,  11383,   3687,   4759,   5489,   3732,
         8189,   4578,  50988,  10219,  12687,  11274,  19335,    515,
        16575,   1741,  15650,   7653,   6129,    640,   3732,   4389,
          471,   7493,   6913, 316415,    470,  24081,    813,  16225,
        24850,   6317,  17031,    876,  40022,   1425,  25800,    461,
          456,   1648,   8207,   5922,   1408,  18370,   4866,   7927,
         9378,  30388,  11835,   8407,   5212,   7688,  21285,  20475,
        39640,    662,  34950,  13666,  24754,  24174,    505,   2699,
        16462,   4613,    629, 369660,   1647,    566,  12222, 363836,
         3382,  15863,  11296,   2906,    716,  39342,   2189,    843,
         5822,   5662,  41288,   9004,   5237,    638,   3868,  15523,
      